name: Tests

on:
  push:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Runs the tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js from .node-version
        uses: actions/setup-node@v3
        with:
          node-version-file: './energy/.node-version'
          cache: "npm"
          cache-dependency-path: "energy/package-lock.json"

      - name: Install dependencies
        working-directory: ./energy
        run: |
          npm ci

      - name: Run tests
        working-directory: ./energy
        run: npm test
