name: Tests

on:
  push:
    branches:
      - main # run when pushing to main
  pull_request:
    branches: ["*"] # run when PR

permissions:
  contents: read

jobs:
  test:
    name: Runs the tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js from .node-version
        uses: actions/setup-node@v3
        with:
          node-version-file: "./.node-version"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install dependencies
        working-directory: ./
        run: |
          npm ci

      - name: Run API tests
        run: npm run --workspace=api test
        working-directory: ./
        env:
          FORCE_COLOR: 3 # Enable color output
