name: Tests

on:
  push:
    branches-ignore:
      - main # do not run when pushing to main
  pull_request:
    branches: [main] # run when PR targets main

jobs:
  test:
    name: Runs the tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js from .node-version
        uses: actions/setup-node@v3
        with:
          node-version-file: "./.node-version"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install dependencies
        working-directory: ./
        run: |
          npm ci

      - name: Run API tests
        run: |
          echo "::group::Test Output"
          echo "::debug::" # Enable debug mode for better formatting
          npm --workspace=api run test
          echo "::endgroup::"
        working-directory: ./
        env:
          FORCE_COLOR: 3 # Enable color output
          GITHUB_STEP_SUMMARY: |-
            ```js
            ${{ steps.test.outputs.summary }}
            ```
