name: Security Scan

on:
  push:
    branches:
      - main # run when pushing to main
  pull_request:
    branches: ["*"] # run when PR

permissions:
  contents: read

jobs:
  security:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
